Welcome to #b#cffffdd66FlyForFun.io#nc#nb !

This project is still at a prototype stage, however it #bcollects users datas#nb for its efficiency and safety.

Are collected: your IP address, your login and logout dates, datas liked to your virtual characters (name, location, inventory...). Their only aim is to enable you to try the prototype and will be completely delated by the end of 2019. The datas are saved on a secured server under the responsibility of #bLoïc Saos#nb, computer science engineering student. In case of any question or request concerning datas' removal, please, use the following address:
#blsaos@flyforfun.io#nb.

This website also use the persistent memory of your computer in order to store your session ID and your display preferences. In case you feel the need to, you may delate those datas without any further consequences.

Through this website you may communicate with other users. Any comments not aligned to French law, including but not limited to racists, homophobic, harassment and discriminatory comments are strictly forbidden. In case of non-respect of those rules, moderators take the right of immediate removal or block of your character, and even to forbid the access to the server from your IP address.

By clicking on the button #cffffdd66Accept#nc you certify you learned of the mentions above and accept it.