Bienvenue sur #b#cffffdd66FlyForFun.io#nc#nb !

Le projet est au stade de prototype, toutefois il #bcollecte des données sur les utilisateurs#nb pour son fonctionnement et sa sécurité.

Les données collectées sont votre adresse IP, vos dates de connexion et déconnexion, ainsi que les données liées à vos personnages virtuels (nom, position, inventaire...). Ces données ont pour unique but de vous permettre de tester le prototype et seront complètement effacées au plus tard le 31 décembre 2019. Ces données sont stockées sur un serveur sécurisé dont le responsable est #bLoïc Saos#nb, élève-ingénieur en informatique. Pour toute question ou demande de suppression de ces données, merci de le contacter par email à l'adresse
#blsaos@flyforfun.io#nb.

Ce site internet utilise également la mémoire persistante de votre ordinateur pour stocker votre identifiant de session et vos préférences d'affichage. Si besoin, vous pouvez supprimer ces données sans conséquences.

Ce site internet permet de communiquer avec d'autres utilisateurs. Tous les propos ne respectant pas la loi française, y compris mais sans limitation les propos racistes, homophobes, harcelants, discriminatoires sont strictement interdits. Si vous ne respectez pas cette règle, les modérateurs se réservent le droit immédiat de bloquer ou supprimer votre personnage, voire d'interdire l'accès au serveur depuis votre adresse IP.

En cliquant sur le bouton #cffffdd66Accepter#nc vous affirmez avoir pris connaissance des mentions ci-dessus et les acceptez.